import os, json

# These are the files generated by your other ETL scripts
FILES = [
    "/opt/airflow/data/processed_csv.json",
    "/opt/airflow/data/processed_logs.json",
    "/opt/airflow/data/processed_api.json"
]

def run_quality_check():
    for file_path in FILES:
        # 1. Check if the file actually exists
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"Quality Check Failed: Missing file -> {file_path}")
        
        # 2. Check if the file contains data
        with open(file_path, "r") as file:
            data = json.load(file)
            if not data or len(data) == 0:
                raise ValueError(f"Quality Check Failed: File is empty -> {file_path}")
                
    print("[QUALITY GATE] All processed files exist and contain data. Proceeding to load phase.")

if __name__ == "__main__":
    run_quality_check()